/**
 * This is the Notion as Code script example compiled by runNotionAsCode.ts.
 *
 * The teamspace, page, database, and database entries below are new resources
 * that will be created in the workspace you have provided when running the script.
 *
 * Try changing names, page content, properties, or add more entries, then rerun
 * the example.
 *
 * Note: The resourceIds below are stable and will let future runs update the same resources.
 */

// The "example-space" resourceId anchors this script to the workspace provided
// with --spaceId. The runner maps that resourceId to the workspace on first run.
const spaceParent = {
  type: "resourceId",
  resourceId: "example-space",
} as const

// This creates the new General teamspace inside that mapped workspace.
const generalTeamspace = notion.teamspace({
  resourceId: "general-teamspace",
  // Set this teamspace's parent to the workspace referenced by spaceParent.
  parent: spaceParent,
  name: "General",
  accessLevel: "open",
  icon: { type: "notion_icon", description: "home", color: "lightgray" },
  description: "A starting point created by Notion as Code.",
})

// This creates a top-level page in the General teamspace with an icon, title, and content.
generalTeamspace.addPage({
  resourceId: "hello-world-page",
  properties: { title: notion.text("Hello world!") },
  icon: { type: "notion_icon", description: "sparkles", color: "yellow" },
  // This is the content of the page. It is written in Notion-flavored markdown.
  // Below, we've included examples of different blocks: heading 1, callout, and @ date mention.
  content: `# Congratulations

<callout icon="🎉">
You've successfully generated Notion resources with Notion as Code!
</callout>

Continue using this space to try out generated pages, databases, and seed content.
<mention-date start="2026-07-10"/>
`,
})

// This creates a database in the General teamspace with some sample projects.
const sampleDatabase = generalTeamspace.addDatabase({
  resourceId: "sample-projects-db",
  name: "Sample Projects",
  icon: { type: "notion_icon", description: "database", color: "purple" },
  description: "A small seeded database generated by Notion as Code.",
  dataSources: [
    {
      resourceId: "sample-projects-ds",
      name: "Sample Projects",
      // This array defines the properties that database pages can set.
      // The resourceIds below are stable and will let future runs update the same columns.
      properties: [
        { resourceId: "project-name-prop", name: "Name", type: "title" },
        {
          resourceId: "project-status-prop",
          name: "Status",
          type: "status",
          options: {
            todo: [{ name: "Not Started", color: "gray", default: true }],
            inProgress: [{ name: "In Progress", color: "blue" }],
            complete: [{ name: "Done", color: "green" }],
          },
        },
        {
          resourceId: "project-priority-prop",
          name: "Priority",
          type: "select",
          options: [
            { name: "High", color: "red" },
            { name: "Medium", color: "yellow" },
            { name: "Low", color: "green" },
          ],
        },
        {
          resourceId: "project-target-date-prop",
          name: "Target",
          type: "date",
        },
        { resourceId: "project-notes-prop", name: "Notes", type: "text" },
      ],
    },
  ],
})

// Get the data source handle so we can add sample entries to the database.
// "sample-projects-ds" matches the resourceId of the data source we created above.
const sampleProjects = sampleDatabase.getDataSource("sample-projects-ds")

// These database pages are sample entries. We've created three sample pages below with varying properties.
// You can try adding more pages of your own -- just make sure to change the resourceId.
sampleProjects.addPage({
  resourceId: "review-generated-workspace",
  properties: {
    Name: notion.text("Review generated workspace"),
    Status: notion.status("Done"),
    Priority: notion.select("High"),
    Target: notion.date("2026-07-08"),
    Notes: notion.text("Confirm the General teamspace and hello page."),
  },
})

sampleProjects.addPage({
  resourceId: "invite-teammates",
  properties: {
    Name: notion.text("Invite teammates"),
    Status: notion.status("In Progress"),
    Priority: notion.select("Medium"),
    Target: notion.date("2026-07-15"),
    Notes: notion.text("Share the generated workspace with collaborators."),
  },
})

sampleProjects.addPage({
  resourceId: "customize-sample-database",
  properties: {
    Name: notion.text("Customize sample database"),
    Status: notion.status("Not Started"),
    Priority: notion.select("Low"),
    Target: notion.date("2026-07-22"),
    Notes: notion.text("Adjust properties, views, and seed entries."),
  },
  // You can add content to database pages too, just like regular pages!
  // More block types featured in this example: quote, divider, bulleted list.
  content: `> This is a quote block.
---

This is a divider block.

---

This is a bulleted list:
- Item 1
- Item 2
- Item 3
`,
})

export {}
