// Generated by notion public-api update-sdk-js. Do not edit.
import type Client from "./Client"
import type { RequestParameters } from "./Client"
import * as endpoints from "./api-endpoints"
import { pick, type EndpointDefinition } from "./utils"

type WithoutIndexSignatures<P> = P extends unknown
  ? {
      [K in keyof P as string extends K
        ? never
        : number extends K
          ? never
          : K]: P[K]
    }
  : never
type WithAuth<P> = P & { auth?: string }
type OptionalWithAuth<P> = WithoutIndexSignatures<P> & { auth?: string }
type EndpointClient = Pick<Client, "request"> & {
  warnUnknownParams(
    args: Record<string, unknown>,
    endpoint: EndpointDefinition
  ): void
}

export function createEndpointMethods(client: EndpointClient) {
  function method<P extends Record<string, unknown>, R extends object>(
    definition: EndpointDefinition & {
      path: (args: P) => string
      method: RequestParameters["method"]
      headers?: Record<string, string>
    },
    query: (args: WithAuth<P>) => RequestParameters["query"]
  ): (args: WithAuth<P>) => Promise<R> {
    return args => {
      client.warnUnknownParams(args, definition)
      return client.request<R>({
        path: definition.path(args),
        method: definition.method,
        query: query(args),
        body: pick<Record<string, unknown>, string>(
          args,
          definition.bodyParams
        ),
        ...(definition.headers ? { headers: definition.headers } : {}),
        auth: args?.auth,
      })
    }
  }
  function optionalMethod<P extends Record<string, unknown>, R extends object>(
    definition: EndpointDefinition & {
      path: () => string
      method: RequestParameters["method"]
      headers?: Record<string, string>
    },
    query: (args: Partial<OptionalWithAuth<P>>) => RequestParameters["query"]
  ): (args?: OptionalWithAuth<P>) => Promise<R> {
    return args => {
      const requestArgs: Partial<OptionalWithAuth<P>> = args ?? {}
      client.warnUnknownParams(requestArgs, definition)
      return client.request<R>({
        path: definition.path(),
        method: definition.method,
        query: query(requestArgs),
        body: pick<Record<string, unknown>, string>(
          requestArgs,
          definition.bodyParams
        ),
        ...(definition.headers ? { headers: definition.headers } : {}),
        auth: requestArgs.auth,
      })
    }
  }
  return {
    users: {
      /** Retrieve your token's bot user */
      me: optionalMethod<
        endpoints.GetSelfParameters,
        endpoints.GetSelfResponse
      >(endpoints.getSelf, args => pick(args, endpoints.getSelf.queryParams)),
      /** Retrieve a user */
      retrieve: method<endpoints.GetUserParameters, endpoints.GetUserResponse>(
        endpoints.getUser,
        args => pick(args, endpoints.getUser.queryParams)
      ),
      /** List all users */
      list: optionalMethod<
        endpoints.ListUsersParameters,
        endpoints.ListUsersResponse
      >(endpoints.listUsers, args =>
        pick(args, endpoints.listUsers.queryParams)
      ),
    },
    pages: {
      /** Create a page */
      create: method<
        endpoints.CreatePageParameters,
        endpoints.CreatePageResponse
      >(endpoints.createPage, args =>
        pick(args, endpoints.createPage.queryParams)
      ),
      /** Retrieve a page */
      retrieve: method<endpoints.GetPageParameters, endpoints.GetPageResponse>(
        endpoints.getPage,
        args => pick(args, endpoints.getPage.queryParams)
      ),
      /** Update page */
      update: method<
        endpoints.UpdatePageParameters,
        endpoints.UpdatePageResponse
      >(endpoints.updatePage, args =>
        pick(args, endpoints.updatePage.queryParams)
      ),
      /** Move a page */
      move: method<endpoints.MovePageParameters, endpoints.MovePageResponse>(
        endpoints.movePage,
        args => pick(args, endpoints.movePage.queryParams)
      ),
      properties: {
        /** Retrieve a page property item */
        retrieve: method<
          endpoints.GetPagePropertyParameters,
          endpoints.GetPagePropertyResponse
        >(endpoints.getPageProperty, args =>
          pick(args, endpoints.getPageProperty.queryParams)
        ),
      },
    },
    asyncTasks: {
      /** Retrieve an async task */
      retrieve: method<
        endpoints.GetAsyncTaskParameters,
        endpoints.GetAsyncTaskResponse
      >(endpoints.getAsyncTask, args =>
        pick(args, endpoints.getAsyncTask.queryParams)
      ),
    },
    blocks: {
      /** Retrieve a block */
      retrieve: method<
        endpoints.GetBlockParameters,
        endpoints.GetBlockResponse
      >(endpoints.getBlock, args => pick(args, endpoints.getBlock.queryParams)),
      /** Update a block */
      update: method<
        endpoints.UpdateBlockParameters,
        endpoints.UpdateBlockResponse
      >(endpoints.updateBlock, args =>
        pick(args, endpoints.updateBlock.queryParams)
      ),
      /** Delete a block */
      delete: method<
        endpoints.DeleteBlockParameters,
        endpoints.DeleteBlockResponse
      >(endpoints.deleteBlock, args =>
        pick(args, endpoints.deleteBlock.queryParams)
      ),
      children: {
        /** Retrieve block children */
        list: method<
          endpoints.ListBlockChildrenParameters,
          endpoints.ListBlockChildrenResponse
        >(endpoints.listBlockChildren, args =>
          pick(args, endpoints.listBlockChildren.queryParams)
        ),
        /** Append block children */
        append: method<
          endpoints.AppendBlockChildrenParameters,
          endpoints.AppendBlockChildrenResponse
        >(endpoints.appendBlockChildren, args =>
          pick(args, endpoints.appendBlockChildren.queryParams)
        ),
      },
      meetingNotes: {
        /** Create a meeting note */
        create: method<
          endpoints.CreateMeetingNoteParameters,
          endpoints.CreateMeetingNoteResponse
        >(endpoints.createMeetingNote, args =>
          pick(args, endpoints.createMeetingNote.queryParams)
        ),
      },
    },
    dataSources: {
      /** Retrieve a data source */
      retrieve: method<
        endpoints.GetDataSourceParameters,
        endpoints.GetDataSourceResponse
      >(endpoints.getDataSource, args =>
        pick(args, endpoints.getDataSource.queryParams)
      ),
      /** Update a data source */
      update: method<
        endpoints.UpdateDataSourceParameters,
        endpoints.UpdateDataSourceResponse
      >(endpoints.updateDataSource, args =>
        pick(args, endpoints.updateDataSource.queryParams)
      ),
      /** Query a data source */
      query: method<
        endpoints.QueryDataSourceParameters,
        endpoints.QueryDataSourceResponse
      >(endpoints.queryDataSource, args =>
        pick(args, endpoints.queryDataSource.queryParams)
      ),
      /** Create a data source */
      create: method<
        endpoints.CreateDataSourceParameters,
        endpoints.CreateDataSourceResponse
      >(endpoints.createDataSource, args =>
        pick(args, endpoints.createDataSource.queryParams)
      ),
      /** List templates in a data source */
      listTemplates: method<
        endpoints.ListDataSourceTemplatesParameters,
        endpoints.ListDataSourceTemplatesResponse
      >(endpoints.listDataSourceTemplates, args =>
        pick(args, endpoints.listDataSourceTemplates.queryParams)
      ),
    },
    databases: {
      /** Retrieve a database */
      retrieve: method<
        endpoints.GetDatabaseParameters,
        endpoints.GetDatabaseResponse
      >(endpoints.getDatabase, args =>
        pick(args, endpoints.getDatabase.queryParams)
      ),
      /** Update a database */
      update: method<
        endpoints.UpdateDatabaseParameters,
        endpoints.UpdateDatabaseResponse
      >(endpoints.updateDatabase, args =>
        pick(args, endpoints.updateDatabase.queryParams)
      ),
      /** Create a database */
      create: method<
        endpoints.CreateDatabaseParameters,
        endpoints.CreateDatabaseResponse
      >(endpoints.createDatabase, args =>
        pick(args, endpoints.createDatabase.queryParams)
      ),
    },
    /** Search by title */
    search: optionalMethod<
      endpoints.SearchParameters,
      endpoints.SearchResponse
    >(endpoints.search, args => pick(args, endpoints.search.queryParams)),
    comments: {
      /** Create a comment */
      create: method<
        endpoints.CreateCommentParameters,
        endpoints.CreateCommentResponse
      >(endpoints.createComment, args =>
        pick(args, endpoints.createComment.queryParams)
      ),
      /** List comments */
      list: method<
        endpoints.ListCommentsParameters,
        endpoints.ListCommentsResponse
      >(endpoints.listComments, args =>
        pick(args, endpoints.listComments.queryParams)
      ),
      /** Retrieve a comment */
      retrieve: method<
        endpoints.GetCommentParameters,
        endpoints.GetCommentResponse
      >(endpoints.getComment, args =>
        pick(args, endpoints.getComment.queryParams)
      ),
      /** Update a comment */
      update: method<
        endpoints.UpdateCommentParameters,
        endpoints.UpdateCommentResponse
      >(endpoints.updateComment, args =>
        pick(args, endpoints.updateComment.queryParams)
      ),
      /** Delete a comment */
      delete: method<
        endpoints.DeleteCommentParameters,
        endpoints.DeleteCommentResponse
      >(endpoints.deleteComment, args =>
        pick(args, endpoints.deleteComment.queryParams)
      ),
    },
    fileUploads: {
      /** Create a file upload */
      create: optionalMethod<
        endpoints.CreateFileUploadParameters,
        endpoints.CreateFileUploadResponse
      >(endpoints.createFileUpload, args =>
        pick(args, endpoints.createFileUpload.queryParams)
      ),
    },
    views: {
      /** List views */
      list: optionalMethod<
        endpoints.ListDatabaseViewsParameters,
        endpoints.ListDatabaseViewsResponse
      >(endpoints.listDatabaseViews, args =>
        pick(args, endpoints.listDatabaseViews.queryParams)
      ),
      /** Retrieve a view */
      retrieve: method<endpoints.GetViewParameters, endpoints.GetViewResponse>(
        endpoints.getView,
        args => pick(args, endpoints.getView.queryParams)
      ),
      /** Delete a view */
      delete: method<
        endpoints.DeleteViewParameters,
        endpoints.DeleteViewResponse
      >(endpoints.deleteView, args =>
        pick(args, endpoints.deleteView.queryParams)
      ),
      queries: {
        /** Get view query results */
        results: method<
          endpoints.GetViewQueryResultsParameters,
          endpoints.GetViewQueryResultsResponse
        >(endpoints.getViewQueryResults, args =>
          pick(args, endpoints.getViewQueryResults.queryParams)
        ),
        /** Delete a view query */
        delete: method<
          endpoints.DeleteViewQueryParameters,
          endpoints.DeleteViewQueryResponse
        >(endpoints.deleteViewQuery, args =>
          pick(args, endpoints.deleteViewQuery.queryParams)
        ),
      },
    },
    agents: {
      /** Query agents */
      query: optionalMethod<
        endpoints.QueryAgentsParameters,
        endpoints.QueryAgentsResponse
      >(endpoints.queryAgents, args =>
        pick(args, endpoints.queryAgents.queryParams)
      ),
      /** Get agent */
      retrieve: method<
        endpoints.GetAgentParameters,
        endpoints.GetAgentResponse
      >(endpoints.getAgent, args => pick(args, endpoints.getAgent.queryParams)),
      /** Delete agent */
      delete: method<
        endpoints.DeleteAgentParameters,
        endpoints.DeleteAgentResponse
      >(endpoints.deleteAgent, args =>
        pick(args, endpoints.deleteAgent.queryParams)
      ),
      /** Get agent insights */
      retrieveInsights: method<
        endpoints.GetInsightsParameters,
        endpoints.GetInsightsResponse
      >(endpoints.getInsights, args =>
        pick(args, endpoints.getInsights.queryParams)
      ),
      /** Update agent status */
      updateStatus: method<
        endpoints.UpdateAgentStatusParameters,
        endpoints.UpdateAgentStatusResponse
      >(endpoints.updateAgentStatus, args =>
        pick(args, endpoints.updateAgentStatus.queryParams)
      ),
      /** Update agent credit limit */
      updateCreditLimit: method<
        endpoints.UpdateAgentCreditLimitParameters,
        endpoints.UpdateAgentCreditLimitResponse
      >(endpoints.updateAgentCreditLimit, args =>
        pick(args, endpoints.updateAgentCreditLimit.queryParams)
      ),
      /** Apply many agent operations */
      batch: method<
        endpoints.AgentBatchParameters,
        endpoints.AgentBatchResponse
      >(endpoints.agentBatch, args =>
        pick(args, endpoints.agentBatch.queryParams)
      ),
    },
    sessions: {
      /** Update a session */
      update: method<
        endpoints.UpdateSessionParameters,
        endpoints.UpdateSessionResponse
      >(endpoints.updateSession, args =>
        pick(args, endpoints.updateSession.queryParams)
      ),
      /** Retrieve a session */
      retrieve: method<
        endpoints.RetrieveSessionParameters,
        endpoints.RetrieveSessionResponse
      >(endpoints.retrieveSession, args =>
        pick(args, endpoints.retrieveSession.queryParams)
      ),
      /** Query sessions */
      query: optionalMethod<
        endpoints.QuerySessionsParameters,
        endpoints.QuerySessionsResponse
      >(endpoints.querySessions, args =>
        pick(args, endpoints.querySessions.queryParams)
      ),
      /** Query session events */
      queryEvents: method<
        endpoints.QuerySessionEventsParameters,
        endpoints.QuerySessionEventsResponse
      >(endpoints.querySessionEvents, args =>
        pick(args, endpoints.querySessionEvents.queryParams)
      ),
      /** Cancel a session */
      cancel: method<
        endpoints.CancelSessionParameters,
        endpoints.CancelSessionResponse
      >(endpoints.cancelSession, args =>
        pick(args, endpoints.cancelSession.queryParams)
      ),
    },
  }
}
