FROM ubuntu:18.04
RUN apt update
RUN apt install -y git wget
RUN wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
RUN dpkg -i pandoc-2.18-1-amd64.deb
ENTRYPOINT [ "/bin/bash" ]
