name: Security - Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: "20 17 * * *"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    timeout-minutes: 480
    steps:
      # v5.0.0
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP }}
